M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date So 10 Dez 2023 20:03:15 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-10T20:03:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X144.97Y-118.3
X144.97Y-123.15
T2
X148.0Y-118.0
X148.0Y-123.45
T3
X65.0Y-95.0
X65.0Y-130.0
X145.5Y-95.0
T0
M30
